site_name: OTTO Docs 
site_description: OTTO Documentation
site_favicon: '/img/otto_favicon.ico'
copyright: IPR Terms will be defined by Kantara Work Group charter
docs_dir: sources
repo_url: https://github.com/nynymike/otto/docs
theme: spacelab

theme_dir: ./theme/mkdocs/
theme_center_lead: false
include_search: true

pages:

# Home Page
- ['index.md', 'Home']
- ['charter.md', 'Charter']
- ['schedule.md', 'Schedule']

# Schema Sections
- ['schema/openid.md', 'Schema', 'OpenID']
- ['schema/uma.md', 'Schema', 'UMA']
- ['schema/federation.md', 'Schema', 'Federation']

# API section
- ['api/discovery.md', 'API', 'discovery']
- ['api/register.md', 'API', 'register']
- ['api/metadata.md', 'API', 'metadata']

